### ISSUE TITLE
Chicago legislation hasn't updated since 11/04/2019

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#265]
Viewing https://chicago.councilmatic.org/search/ it looks like legislation has not updated for at least 7 months:

<img width="1278" alt="Screen Shot 2020-07-20 at 11 54 48 AM" src="https://user-images.githubusercontent.com/919583/87964522-fb0fde80-ca7f-11ea-8dce-e9d2c2402cf9.png">

We should investigate and get the legislation updated. The site does not have much value with stale data.

**Comment by hancush** [comment]
Bills are being imported:

```python
# On the server
>>> ChicagoBill.objects.aggregate(latest_update=Max('updated_at'))
{'latest_update': datetime.datetime(2020, 8, 7, 15, 28, 46, 671842, tzinfo=<UTC>)}
```

So I reasoned this had to do with indexing. Manually triggered a bill indexing operation, and behold, it breaks:

```bash
(chicago)datamade@ip-10-0-0-124:~/chicago$ python manage.py update_index --batch-size=250
Indexing 114693 chicago bills
[10:31:13][INFO] pysolr pysolr.py:_send_request:402 | Finished 'http://127.0.0.1:8983/solr/chicago/update/?commit=true' (post) with body '<add><doc ' in 1.102 seconds, with status 400
[10:31:13][ERROR] pysolr pysolr.py:_send_request:411 | Solr responded with an error (HTTP 400): [Reason: Invalid Date String:'2015-07-29']
Failed to add documents to Solr: Solr responded with an error (HTTP 400): [Reason: Invalid Date String:'2015-07-29']
Traceback (most recent call last):
  File "/home/datamade/.virtualenvs/chicago/lib/python3.4/site-packages/haystack/backends/solr_backend.py", line 76, in update
    self.conn.add(docs, commit=commit, boost=index.get_field_weights())
  File "/home/datamade/.virtualenvs/chicago/lib/python3.4/site-packages/pysolr.py", line 918, in add
    overwrite=overwrite, handler=handler)
  File "/home/datamade/.virtualenvs/chicago/lib/python3.4/site-packages/pysolr.py", line 500, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "/home/datamade/.virtualenvs/chicago/lib/python3.4/site-packages/pysolr.py", line 412, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
pysolr.SolrError: Solr responded with an error (HTTP 400): [Reason: Invalid Date String:'2015-07-29']
```

So I'll take a looksie.
