### ISSUE TITLE
Sponsors are in wrong order, primary sponsor is wrong

### ISSUE THREAD

**Issue by fgregg** [datamade/chi-councilmatic#92]
I'll fix this in scrapers-municipal

**Comment by fgregg** [comment]
I fixed this on ocd, and ran loaddata again, but the data did not seem to update.

For this bill, Michelle Smith is the primary sponsor:

http://ocd.datamade.us/ocd-bill/bda0f5ad-18b4-47b2-9b14-58ecc556d64d/

but chicouncilmatic is showing it as brian hopkins

http://chicouncilmatic.datamade.us/legislation/o-2015-4229/

**Comment by fgregg** [comment]
Saw this error message running a cron_jobs bash file. Troublingly, these error messages did not get into the log file.

```python
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.4/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 78, in worker
    do_update(backend, index, qs, start, end, total, verbosity=verbosity, commit=commit)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 96, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/haystack/backends/solr_backend.py", line 75, in update
    self.conn.add(docs, commit=commit, boost=index.get_field_weights())
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/pysolr.py", line 813, in add
    return self._update(m, commit=commit, softCommit=softCommit, waitFlush=waitFlush, waitSearcher=waitSearcher)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/pysolr.py", line 397, in _update
    message = sanitize(message)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/pysolr.py", line 1086, in sanitize
    return force_unicode(fixed_string)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/pysolr.py", line 107, in force_unicode
    value = value.decode('utf-8', errors='replace')
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
    self.update_backend(label, using)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 239, in update_backend
    pool.map(worker, ghetto_queue)
  File "/usr/local/lib/python3.4/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
MemoryError
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.4/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 78, in worker
    do_update(backend, index, qs, start, end, total, verbosity=verbosity, commit=commit)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 96, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/haystack/backends/solr_backend.py", line 75, in update
    self.conn.add(docs, commit=commit, boost=index.get_field_weights())
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/pysolr.py", line 813, in add
    return self._update(m, commit=commit, softCommit=softCommit, waitFlush=waitFlush, waitSearcher=waitSearcher)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/pysolr.py", line 397, in _update
    message = sanitize(message)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/pysolr.py", line 1086, in sanitize
    return force_unicode(fixed_string)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/pysolr.py", line 107, in force_unicode
    value = value.decode('utf-8', errors='replace')
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 183, in handle
    return super(Command, self).handle(*items, **options)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/django/core/management/base.py", line 622, in handle
    label_output = self.handle_label(label, **options)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
    self.update_backend(label, using)
  File "/home/datamade/.virtualenvs/chi-councilmatic/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 239, in update_backend
    pool.map(worker, ghetto_queue)
  File "/usr/local/lib/python3.4/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
MemoryError
```

**Comment by fgregg** [comment]
This depends on https://github.com/opencivicdata/pupa/issues/226
